### ISSUE TITLE
SwapScope fails when the user has not logged in before and selected a non-default update set.

### ISSUE THREAD

**Issue by collinparker-nuvolo** [nuvolo/sincronia#122]
TypeError: Cannot read property 'sys_id' of undefined
(node:7155) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sys_id' of undefined
    at Object.getCurrentUpdateSetUserPref (/Users/runner/runners/2.170.1/work/1/s/packages/nps/node_modules/@sincronia/core/dist/server.js:365:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async AppManager.createAndAssignUpdateSet (/Users/runner/runners/2.170.1/work/1/s/packages/nps/node_modules/@sincronia/core/dist/AppManager.js:592:52)
    at async /Users/runner/runners/2.170.1/work/1/s/packages/nps/node_modules/@sincronia/core/dist/commands.js:79:17
(node:7155) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7155) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by collinparker-nuvolo** [comment]
to recreate this issue, create a new user and use that user to do a `sinc push` with the --ss option flag.

**Comment by collinparker-nuvolo** [comment]
seems to be specific with cloning process, cannot reproduce
