### ISSUE TITLE
Failed to setup application.

### ISSUE THREAD

**Issue by kylecribbs** [nuvolo/sincronia#140]
We are an On-Prem instance and we are unable to connect via `npx sinc init` we keep getting 
```
Failed to setup application. Check to see that your credentials are correct and you have the update set installed on your instance.
```

We have our own CA's and internal domain. 

Is there a way to turn on debugging to see why it cannot connect?

**Comment by kylecribbs** [comment]
I created my .env file and tried running `npx sinc dev` and i get:
```
(node:2137) UnhandledPromiseRejectionWarning: Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1474:34)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket._finishInit (_tls_wrap.js:917:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:687:12)
(node:2137) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2137) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Which means its not trusting my CA. I have the CA installed correctly on Ubunut so it sounds like sinc or npm is not using the installed CAs. I tried adding the certs in my npmrc and still same error.

**Comment by kylecribbs** [comment]
Tested... Running
```javascript
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
```
works. 

Can we do a merge request for allowing insecure or allowing custom CA's?

**Comment by bbarber9** [comment]
Hello!

This is an interesting problem. We haven't had any on-prem instances to test with so this is very valuable feedback! 

We certainly allow pull requests if you are interested in submitting a fix. Looks like turning off the authorized cert check works as a bandaid. I wonder if there's a way to get it to just recognize your cert? I guess some more digging is required here

**Comment by bbarber9** [comment]
It looks like [axios](https://github.com/axios/axios) (the client we use to connect to the instance) supports you supplying a custom https agent from the [https node module](https://nodejs.org/api/https.html#https_class_https_agent). We will probably have to find a way to allow someone configure that I bet

**Comment by kylecribbs** [comment]
I was thinking of adding 2 solutions.

1) a -k similar to curl where it allows insecure connection
2) passing an https agent with a ENV var to a cert bundle

thoughts?

**Comment by bbarber9** [comment]
I like those ideas! Nice and flexible. Let me know if you have any questions on how to implement it

**Comment by kylecribbs** [comment]
Only thing I need help with is how to build locally for testing. Not familiar with building CLIs with typescript/JavaScript

**Comment by bbarber9** [comment]
Sure here's a brief overview of how you can get setup.

Install a couple of the necessary tools globally for convenience

```bash
npm install -g typescript lerna ts-node
```
Clone the repo, create your branch etc., and run the following
```bash
#links all the local packages together
lerna bootstrap
```
Then you will want to move into the core package by changing to the `packages/core` directory.
You will want to edit the typescript code while implementing your features and then you have a couple options for building and running it.
1. run the `tsc` command to produce some javascript you can run under a dist folder. You want to run `node index.js`
2. run `ts-node` on the typescript directly and it should run I think. This will build it in memory and not produce any files.

Running either of those options is equivalent to running `npx sinc`, you can provide options after them just like the normal command. 

Let me know if that doesn't make sense
