### ISSUE TITLE
Implement retry mechanism for pushing files that fail from network issues

### ISSUE THREAD

**Issue by collinparker-nuvolo** [nuvolo/sincronia#85]
Failed to push sys_script_include/SecurityNVDParser(9ecf999d0ff37e00429585ace1050edc)
Error: socket hang up
    at connResetException (internal/errors.js:604:14)
    at TLSSocket.socketOnEnd (_http_client.js:460:23)
    at TLSSocket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET',

**Comment by collinparker-nuvolo** [comment]
if file still fails to push after retry limit hits this should throw an error code so the pipeline knows it was not completely successful
